//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vieon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int ID_BinhLuan { get; set; }
        public Nullable<int> ID_Phim { get; set; }
        public Nullable<int> ID_User { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
    
        public virtual Phim Phim { get; set; }
        public virtual User User { get; set; }
    }
}
