//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vieon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim_DaoDien
    {
        public int ID_Phim_DaoDien { get; set; }
        public Nullable<int> ID_Phim { get; set; }
        public Nullable<int> ID_DaoDien { get; set; }
        public string VaiTro { get; set; }
    
        public virtual DaoDien DaoDien { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
