//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vieon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TapPhim
    {
        public int ID_TapPhim { get; set; }
        public Nullable<int> ID_Phim { get; set; }
        public Nullable<int> SoTap { get; set; }
        public string TenTap { get; set; }
        public string MoTa { get; set; }
        public string ThoiLuong { get; set; }
        public Nullable<System.DateTime> NgayRaMat { get; set; }
        public string UrlPhim { get; set; }
    
        public virtual Phim Phim { get; set; }
    }
}
